### ISSUE TITLE
fix: Ensure source and medium are captured correctly for donations

### ISSUE THREAD

**Issue by Benunc** [impress-org/give-google-analytics#34]
Source/Medium should be recorded, not undefined:

![schermata-2018-08-04-alle-10-41-52](https://user-images.githubusercontent.com/9629102/43809201-e230f544-9a7e-11e8-9d72-e3db6a9bf76b.png)

I have replicated this in my test environment, so either it's something I and the customer are doing wrong or the issues resolved in #25 are not fully fixed.

### Related
https://secure.helpscout.net/conversation/623784593/21798/

**Comment by ravinderk** [comment]
@Benunc Google analytic tracker does not work for `administrator`, instead of test with the guest donor.

I tried URL like this `http://test1.givewp.com/donations/ga-tracking-test-2/?utm_source=Give_Testing&utm_medium=Give_Testing_Site&utm_campaign=Give_Developer`.

Which sets `give_campaign` properly but rewrite `give_source`, `give_medium` cookie.

@DevinWalker Can you look at this:
set cookie:https://github.com/WordImpress/Give-Google-Analytics/blob/master/includes/actions.php#L245
reset cookie: https://github.com/WordImpress/Give-Google-Analytics/blob/master/includes/actions.php#L234

![image](https://user-images.githubusercontent.com/1784821/43832042-b85cb38e-9b23-11e8-8b81-701b9beef930.png)

**Comment by ravinderk** [comment]
@DevinWalker As i told in this comment: https://github.com/WordImpress/Give-Google-Analytics/issues/34#issuecomment-411361046

After removing this code :https://github.com/WordImpress/Give-Google-Analytics/blob/master/includes/actions.php#L243#23L249

source and medium set properlly in Google analytic

![image](https://user-images.githubusercontent.com/1784821/44670954-c173fb80-aa41-11e8-84e2-34212ab72847.png)

**Comment by DevinWalker** [comment]
@ravinderk please explain _why_ removing that code corrects the issue.

**Comment by Benunc** [comment]
Reopening this. See this video:

https://screencast-o-matic.com/watch/cFQXYeqmaW

**Comment by kevinwhoffman** [comment]
@ravinderk Please review the video from @Benunc and post your findings once you understand why source and medium are lost after a donation is submitted. Thanks.

**Comment by kevinwhoffman** [comment]
@ravinderk Please look into this today and confirm if the issue Ben is showing in the video is still an issue so we can respond to the customer accordingly.

**Comment by DevinWalker** [comment]
Fixed in PR #38
